(()=>{
  const css=`
  .teacherChatFab{position:fixed;right:18px;bottom:18px;z-index:50;border:0;border-radius:999px;background:#0f5f4d;color:white;font-weight:900;padding:14px 18px;box-shadow:0 12px 35px #0004}
  .teacherChat{position:fixed;right:18px;bottom:78px;width:min(420px,calc(100vw - 24px));height:min(620px,calc(100vh - 105px));z-index:51;background:#fffdf9;border:1px solid #eadfd1;border-radius:24px;box-shadow:0 20px 80px #0005;display:none;overflow:hidden;color:#21170f}
  .teacherChat.open{display:flex;flex-direction:column}
  .teacherHead{background:linear-gradient(135deg,#17110b,#0f5f4d);color:white;padding:14px 16px;display:flex;align-items:center;justify-content:space-between;gap:10px}
  .teacherHead b{font-family:Georgia,serif}.teacherHead small{display:block;color:#e8d9c6}.teacherHead button{border:0;background:#ffffff22;color:white;border-radius:10px;padding:7px 10px}
  .teacherMsgs{flex:1;overflow:auto;padding:14px;background:#faf5ee;display:flex;flex-direction:column;gap:10px}
  .teacherMsg{padding:11px 13px;border-radius:16px;max-width:88%;white-space:pre-wrap;line-height:1.45;font-size:14px}.teacherMsg.bot{background:white;border:1px solid #eadfd1;align-self:flex-start}.teacherMsg.user{background:#0f5f4d;color:white;align-self:flex-end}
  .teacherForm{display:flex;gap:8px;padding:12px;border-top:1px solid #eadfd1;background:#fffdf9}.teacherForm textarea{flex:1;min-height:48px;max-height:110px;resize:vertical;border:1px solid #d8c7b6;border-radius:14px;padding:10px;font:inherit}.teacherForm button{border:0;background:#c85a42;color:white;border-radius:14px;padding:0 14px;font-weight:900}
  .teacherQuick{display:flex;gap:7px;flex-wrap:wrap;padding:10px 12px;border-top:1px solid #eadfd1;background:#fffdf9}.teacherQuick button{border:1px solid #d8c7b6;background:white;border-radius:999px;padding:7px 10px;color:#4d3b27;font-size:12px}
  @media(max-width:700px){.teacherChat{left:8px;right:8px;bottom:72px;width:auto;height:min(650px,calc(100vh - 92px));border-radius:18px}.teacherChatFab{right:12px;bottom:12px}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  document.body.insertAdjacentHTML('beforeend',`<button class="teacherChatFab" id="teacherChatFab">💬 Professor</button><section class="teacherChat" id="teacherChat"><div class="teacherHead"><div><b>Professor de Bordado</b><small id="teacherContext">Contexto: módulo atual</small></div><button id="teacherClose">Fechar</button></div><div class="teacherMsgs" id="teacherMsgs"></div><div class="teacherQuick"><button data-q="Explique este módulo de um jeito simples">Explicar módulo</button><button data-q="Quais erros devo evitar neste exercício?">Erros comuns</button><button data-q="Me dê um passo a passo prático para treinar agora">Passo a passo</button><button data-q="Me faça uma pergunta para testar se entendi">Testar aprendizado</button></div><form class="teacherForm" id="teacherForm"><textarea id="teacherInput" placeholder="Pergunte ao professor sobre o módulo atual..."></textarea><button>Enviar</button></form></section>`);
  const panel=document.getElementById('teacherChat'),fab=document.getElementById('teacherChatFab'),close=document.getElementById('teacherClose'),msgs=document.getElementById('teacherMsgs'),form=document.getElementById('teacherForm'),input=document.getElementById('teacherInput'),ctx=document.getElementById('teacherContext');
  function moduleContext(){const title=document.getElementById('nowTitle')?.textContent||'Módulo atual';const summary=document.getElementById('nowText')?.textContent||'';ctx.textContent='Contexto: '+title.replace(/^Módulo \d+ — /,'');return{title,summary,objective:'Ensinar bordado com prática guiada',exercise:'Responder dúvidas do aluno no módulo selecionado'}}
  function add(role,text){const d=document.createElement('div');d.className='teacherMsg '+role;d.textContent=text;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;return d}
  fab.onclick=()=>{panel.classList.add('open');moduleContext();if(!msgs.dataset.started){add('bot','Olá! Eu sou seu professor de bordado. Selecione um módulo e me pergunte qualquer coisa: posso explicar, corrigir erros, passar exercícios e testar seu aprendizado.');msgs.dataset.started='1'}};
  close.onclick=()=>panel.classList.remove('open');
  document.querySelectorAll('.teacherQuick button').forEach(b=>b.onclick=()=>ask(b.dataset.q));
  form.onsubmit=e=>{e.preventDefault();ask(input.value);input.value=''};
  async function ask(question){question=String(question||'').trim();if(!question)return;const mod=moduleContext();add('user',question);const wait=add('bot','Pensando como professor...');try{const r=await fetch('/api/atelier',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'tutor',level:'iniciante',prompt:question,module:mod})});const j=await r.json();wait.textContent=r.ok?(j.text||'Não consegui responder agora.'):(j.error||'Erro no professor. Verifique a chave OpenAI.')}catch(e){wait.textContent='Não consegui conectar ao professor agora.'}msgs.scrollTop=msgs.scrollHeight}
})();
