(()=>{
const $=id=>document.getElementById(id);const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const pad=n=>String(n).padStart(2,'0');
let index=[],cur=1,current=null,audio=null,audioUrl=null;
function setStatus(t){$('status').textContent=t}
async function api(url,opt){const r=await fetch(url,opt);const j=await r.json().catch(()=>({error:'Resposta inválida'}));if(!r.ok)throw new Error(j.error||('Erro '+r.status));return j}
function cardSkeleton(){return `<div class="card"><p>Carregando módulo...</p></div>`}
function renderIndex(){
 $('nav').innerHTML=index.map(m=>`<button onclick="openModule(${m.id})"><b>${pad(m.id)}</b> ${esc(m.title)}</button>`).join('');
 $('gallery').innerHTML=index.slice(0,6).map(m=>`<div class="gal"><span>${esc(m.title)}</span></div>`).join('');
}
function renderModule(m){
 current=m;cur=m.id;localStorage.setItem('curso:lastModule',String(cur));
 $('nowTitle').textContent=`Módulo ${pad(m.id)} — ${m.title}`;$('nowText').textContent=m.summary||'';
 $('bar').style.width=Math.round(m.id/index.length*100)+'%';$('pct').textContent=Math.round(m.id/index.length*100)+'%';
 $('mods').innerHTML=`<article class="card" id="moduleCard"><header><span class="badge">Módulo ${pad(m.id)}</span><h2>${esc(m.title)}</h2></header><div class="moduleImage" id="moduleImage"><span class="fallbackLabel">${esc(m.title)}</span></div><p>${esc(m.summary)}</p><div class="moduleActions"><button class="btn green" id="speakBtn">▶ Ouvir este módulo</button><button class="btn" id="askBtn">💬 Perguntar ao professor</button><button class="btn dark" id="imgBtn">↻ Buscar imagem</button></div><div class="cards3"><div class="box"><b>Apostila</b><p>${(m.charCount||m.content?.length||0).toLocaleString('pt-BR')} caracteres vindos do backend.</p></div><div class="box"><b>Carregamento</b><p>Só este módulo foi baixado agora.</p></div><div class="box"><b>Imagem</b><p>${esc((m.imageQueries||[])[0]||m.imageDescription||m.title)}</p></div></div><details open><summary>Apostila completa</summary><div class="apostila">${esc(m.content||'')}</div></details><details><summary>Descrições de imagem</summary><div class="apostila">${esc([m.imageDescription,...(m.imageQueries||[])].filter(Boolean).join('\n'))}</div></details><div class="credit" id="credit"></div></article>`;
 $('speakBtn').onclick=()=>speakModule(m,$('speakBtn'));$('askBtn').onclick=()=>askModule(m);$('imgBtn').onclick=()=>loadImage(m,true);
 setStatus(`Módulo ${m.id}/${index.length} carregado pelo backend.`);loadImage(m,false);
}
window.openModule=async id=>{try{cur=id;$('mods').innerHTML=cardSkeleton();const m=await api('/api/course/module?id='+id);renderModule(m);document.getElementById('moduleCard')?.scrollIntoView({behavior:'smooth',block:'start'});}catch(e){setStatus(e.message);$('mods').innerHTML=`<div class="card">${esc(e.message)}</div>`}}
async function loadImage(m,force){const key='img:'+m.id;const cached=force?null:localStorage.getItem(key);if(cached){applyImage(JSON.parse(cached));return}const qs=[...(m.imageQueries||[]),m.imageDescription,m.title].filter(Boolean);for(const q of qs){try{$('credit').textContent='Buscando imagem no Pexels...';const j=await api('/api/pexels?query='+encodeURIComponent(q)+'&per_page=1');const img=j.images&&j.images[0];if(img&&img.url){localStorage.setItem(key,JSON.stringify(img));applyImage(img,q);return}}catch(e){$('credit').textContent='Pexels: '+e.message}}}
function applyImage(img,q){$('moduleImage').innerHTML=`<img src="${img.url}" alt="${esc(img.alt||current?.title)}">`;$('credit').textContent='Foto: '+(img.photographer||'Pexels')+(q?' • busca: '+q:'');if(cur===1)$('heroImage').innerHTML=`<img src="${img.url}" alt="${esc(img.alt||'bordado')}">`}
function stopAudio(){if(audio){audio.pause();audio.src='';audio=null}if(audioUrl){URL.revokeObjectURL(audioUrl);audioUrl=null}setStatus('Áudio parado.')}
async function speakModule(m,btn){stopAudio();try{btn.textContent='Gerando áudio...';setStatus('Gerando narração...');const text=(m.title+'\n\n'+m.summary+'\n\n'+m.content).slice(0,3900);const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:'coral',speed:.95})});if(!r.ok)throw new Error('Erro TTS '+r.status);const b=await r.blob();audioUrl=URL.createObjectURL(b);audio=new Audio(audioUrl);audio.onended=()=>{btn.textContent='▶ Ouvir este módulo';setStatus('Narração finalizada.')};await audio.play();btn.textContent='Reproduzindo...';setStatus('Reproduzindo módulo '+m.id)}catch(e){btn.textContent='▶ Ouvir este módulo';setStatus(e.message)}}
$('listenTop').onclick=()=>current&&speakModule(current,$('listenTop'));$('stopBtn').onclick=stopAudio;
function addMsg(cls,t){const d=document.createElement('div');d.className='msg '+cls;d.textContent=t;$('chatMsgs').appendChild(d);$('chatMsgs').scrollTop=$('chatMsgs').scrollHeight;return d}
$('chatFab').onclick=()=>{$('chatBox').classList.add('open');if(!$('chatMsgs').dataset.started){addMsg('bot','Olá! Sou o professor do curso. Faça uma pergunta sobre o módulo atual.');$('chatMsgs').dataset.started=1}}
function askModule(m){$('chatFab').click();$('chatInput').value='Explique este módulo e me dê um exercício prático.';$('chatInput').focus()}
$('chatForm').onsubmit=async e=>{e.preventDefault();const q=$('chatInput').value.trim();if(!q||!current)return;$('chatInput').value='';addMsg('user',q);const wait=addMsg('bot','Pensando como professor...');try{const j=await api('/api/atelier',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'tutor',prompt:q,module:{title:current.title,summary:current.summary,content:(current.content||'').slice(0,2500)}})});wait.textContent=j.text||'Não consegui responder agora.'}catch(e){wait.textContent=e.message}}
$('search').oninput=()=>{const v=$('search').value.toLowerCase();$('nav').innerHTML=index.filter(m=>(m.title+' '+m.summary).toLowerCase().includes(v)).map(m=>`<button onclick="openModule(${m.id})"><b>${pad(m.id)}</b> ${esc(m.title)}</button>`).join('')}
async function boot(){try{setStatus('Carregando índice pelo backend...');const j=await api('/api/course/index');index=j.modules||[];renderIndex();const last=Number(localStorage.getItem('curso:lastModule')||1)||1;await openModule(last)}catch(e){setStatus(e.message);$('mods').innerHTML=`<div class="card">${esc(e.message)}</div>`}}
boot();
})();