const $=id=>document.getElementById(id);const modules=[...COURSE_MODULES_A,...COURSE_MODULES_B].map((m,i)=>({id:i+1,title:m[0],summary:m[1]}));let current=0,presenting=true,timer=null,start=0,audio=$('audio'),audioUrl=null;
function pad(n){return String(n).padStart(2,'0')}function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function longText(m){let txt='';let r=1;while(txt.length<30500){txt+=`\n\nMÓDULO ${pad(m.id)} — ${m.title.toUpperCase()}\n\nContexto histórico e cultural. ${COURSE_BASE}\n\nObjetivos de aprendizagem. ${m.summary} O aluno deve sair deste módulo com repertório técnico, olhar histórico e uma prática documentada em retalho.\n\nConteúdo guiado. Observe o tecido, prepare o bastidor, escolha a linha, defina direção do ponto e trabalhe com respiração regular. A qualidade do bordado nasce da repetição consciente: ponto, pausa, ajuste, observação e continuidade.\n\nPrática ${r}. Execute uma amostra de 12 por 12 centímetros. Fotografe frente e avesso. Anote tensão, tipo de linha, agulha, tempo, erro mais comum e solução aplicada.\n\nErros comuns. Tecido franzido, linha torcida, nó aparente, ponto irregular, desenho deslocado, excesso de tensão e arremate frágil. Corrija em retalho antes de voltar à peça final.\n\nChecklist. Tensão uniforme; pontos legíveis; avesso controlado; desenho centralizado; escolha coerente de tecido; foto final; reflexão escrita; possibilidade de ensinar a técnica.\n`;r++}return txt}

async function enrichImages(){
  const jobs=modules.map(async m=>{
    try{
      const q=encodeURIComponent(`${m.title} embroidery textile art bordado artesanal`);
      const r=await fetch(`/api/pexels?query=${q}&per_page=1`);
      if(!r.ok)return;
      const data=await r.json();
      if(data?.images?.[0])m.image=data.images[0].url;
    }catch(e){console.warn('Falha Pexels',m.title,e)}
  });
  await Promise.all(jobs);
}

function preload(){let i=0;function step(){modules[i].full=longText(modules[i]);i++;let p=Math.round(i/modules.length*100);$('loadbar').style.width=p+'%';$('loadtext').textContent=p+'%';if(i<modules.length)setTimeout(step,8);else{enrichImages().finally(()=>{render();setTimeout(()=>{$('preload').classList.add('done');startPresentation()},300)})}}step()}

function visualCard(title,url){return `<div class="visual" style="background:${url?`url('${url}') center/cover`:'linear-gradient(135deg,#eadcc9,#c85a42,#0f5f4d)'}"><b>${esc(title)}</b></div>`}

function render(){$('nav').innerHTML=modules.map((m,i)=>`<button onclick="go(${i})"><b>${pad(m.id)}</b> ${esc(m.title)}</button>`).join('');$('gallery').innerHTML=modules.slice(0,9).map(v=>visualCard(v.title,v.image)).join('');$('modules').innerHTML=modules.map((m,i)=>`<article id="m${i}" class="card"><header><span class="badge">Módulo ${pad(m.id)}</span><h2>${esc(m.title)}</h2><span class="chars">${m.full.length.toLocaleString('pt-BR')} caracteres</span></header>${m.image?`<img src="${m.image}" alt="${esc(m.title)}" style="width:100%;height:260px;object-fit:cover;border-radius:18px;margin:10px 0 18px;">`:''}<p>${esc(m.summary)}</p><div class="grid3"><div class="box"><b>Objetivo</b><p>Dominar o tema com prática segura.</p></div><div class="box"><b>Prática</b><p>Amostra, foto, avesso e revisão.</p></div><div class="box"><b>Entrega</b><p>Aplicação em mini peça autoral.</p></div></div><details><summary>Abrir apostila completa</summary><div class="full">${esc(m.full)}</div></details><button onclick="speak(${i})">Narrar resumo</button></article>`).join('');update()}

function update(){let m=modules[current];$('slideTitle').textContent=`Módulo ${pad(m.id)} — ${m.title}`;$('slideText').textContent=m.summary;document.querySelectorAll('.card').forEach((e,i)=>e.classList.toggle('active',i===current));let p=Math.round((current+1)/modules.length*100);$('coursebar').style.width=p+'%';$('pct').textContent=p+'%'}
function go(i){current=i;start=performance.now();update();scrollToCurrent()}function next(){go((current+1)%modules.length)}function prev(){go((current-1+modules.length)%modules.length)}function scrollToCurrent(){let el=$('m'+current);if(el)el.scrollIntoView({behavior:'smooth',block:'center'})}
function startPresentation(){presenting=true;start=performance.now();tick()}function tick(){clearTimeout(timer);if(!presenting)return;let e=performance.now()-start;$('slidebar').style.width=Math.min(100,e/6500*100)+'%';if(e>6500){current=(current+1)%modules.length;start=performance.now();update();scrollToCurrent()}timer=setTimeout(tick,120)}
function togglePresent(){presenting=!presenting;$('presentBtn').textContent=presenting?'Pausar apresentação':'Retomar apresentação';if(presenting){start=performance.now();tick()}}
function filter(){let q=$('search').value.toLowerCase();document.querySelectorAll('.card').forEach((e,i)=>e.style.display=(modules[i].title.toLowerCase().includes(q)||modules[i].full.toLowerCase().includes(q))?'block':'none')}
async function speak(i=current){go(i);let m=modules[i];await speakText(`Módulo ${m.id}. ${m.title}. ${m.summary}`)}async function speakText(text){stopAudio(false);$('audioBtn').textContent='Gerando voz...';try{let r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:$('voice').value,speed:.95})});if(!r.ok){let d={};try{d=await r.json()}catch(e){}throw new Error(d.error||'erro no TTS')}let b=await r.blob();if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(b);audio.src=audioUrl;audio.ontimeupdate=()=>{if(audio.duration)window.scrollBy({top:1,behavior:'smooth'})};audio.onended=()=>{$('audioBtn').textContent='Ouvir';$('status').textContent='Narração finalizada.'};await audio.play();$('audioBtn').textContent='Pausar';$('status').textContent='Narração OpenAI em reprodução.'}catch(e){$('audioBtn').textContent='Ouvir';$('status').textContent='Erro na narração: '+e.message}}
function toggleAudio(){if(!audio.paused){stopAudio();return}speak(current)}function stopAudio(up=true){audio.pause();audio.currentTime=0;if(up)$('audioBtn').textContent='Ouvir'}
$('presentBtn').onclick=togglePresent;$('prevBtn').onclick=prev;$('nextBtn').onclick=next;$('audioBtn').onclick=toggleAudio;$('stopBtn').onclick=()=>stopAudio();$('search').oninput=filter;preload();