const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const zlib=require('zlib');
const ROOT=__dirname;
const PORT=process.env.PORT||3000;
const imageCache=new Map();
const audioCache=new Map();
let courseCache=null;
let courseSource='fallback';
function loadEnv(){const p=path.join(ROOT,'.env');if(!fs.existsSync(p))return;for(const line of fs.readFileSync(p,'utf8').split(/\r?\n/)){const t=line.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i<0)continue;const k=t.slice(0,i).trim();let v=t.slice(i+1).trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);if(!process.env[k])process.env[k]=v}}loadEnv();
function clean(v,max=4000){return String(v||'').replace(/\u0000/g,'').replace(/\s+/g,' ').trim().slice(0,max)}
function sendJson(res,status,data,cache='no-store'){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':cache});res.end(JSON.stringify(data))}
function readBody(req,limit=1e6){return new Promise((ok,bad)=>{let b='';req.on('data',c=>{b+=c;if(Buffer.byteLength(b)>limit){bad(new Error('Payload muito grande'));req.destroy()}});req.on('end',()=>ok(b));req.on('error',bad)})}
function hash(v){return crypto.createHash('sha256').update(String(v)).digest('hex')}
function pexelsKey(){let k=(process.env.PEXELS_API_KEY||process.env.PEXELS_KEY||process.env.PEXELS||'').trim();k=k.replace(/^Bearer\s+/i,'').replace(/^PEXELS_API_KEY\s*=\s*/i,'').trim();if((k.startsWith('"')&&k.endsWith('"'))||(k.startsWith("'")&&k.endsWith("'")))k=k.slice(1,-1).trim();return k}
function svgData(title){const safe=String(title||'Imagem do módulo').replace(/[<>&]/g,'');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="760"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#eadfd1"/><stop offset=".55" stop-color="#c85a42"/><stop offset="1" stop-color="#0f5f4d"/></linearGradient></defs><rect width="1200" height="760" fill="url(#g)"/><text x="70" y="590" font-family="Georgia" font-size="46" font-weight="700" fill="white">${safe.slice(0,70)}</text><text x="70" y="655" font-family="Arial" font-size="26" fill="#fff3e8">Imagem ilustrativa do curso de bordado</text></svg>`;return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
const FALLBACK_TITLES=['Arqueologia Têxtil e as Origens do Bordado','Opus Anglicanum e Sacralidade Medieval','Renascimento, Modelbooks e Blackwork','Era Industrial e Máquinas de Bordar','Fibras Naturais e Sintéticas','Ergonomia e Bastidor Profissional','Morfologia dos Pontos','Needle Painting e Degradê','Bordado Branco e Hardanger','Crewel e Estilo Jacobino','Goldwork I: Couching e Or Nué','Goldwork II: Relevo e Purl','Shisha e Espelhamento','Sashiko e Kogin','Zardosi Imperial','Lunéville e Tambour','Pedrarias e Paetês','Stumpwork e Bordado em Relevo','Bordado Brasileiro','Rendas de Agulha e Ponto de Veneza','Conservação e Restauro Têxtil','Design de Padrões','Digitalização e Bordado Computadorizado','Gestão de Ateliê','Curadoria e Exposição','Bordado na Arte Contemporânea','Materiais Não Convencionais','Alfaiataria e Bordado','Fotografia e Documentação Técnica','Projeto Final: Coleção Autoral'];
function fallbackCourse(){courseSource='fallback';return FALLBACK_TITLES.map((title,i)=>({id:i+1,title,summary:'Módulo do curso de bordado.',content:`${title}\n\nConteúdo real do curso ainda não carregado no backend.`,imageDescription:title,imageQueries:[title,'embroidery textile craft'],fallbackImage:svgData(title),charCount:title.length,source:'fallback'}))}
function normalizeModules(parsed,source){const base=parsed?.modules||parsed?.modulos||parsed;if(!Array.isArray(base))throw new Error('Formato de curso inválido');const modules=base.map((m,i)=>({id:Number(m.id||i+1),title:m.title||m.titulo||FALLBACK_TITLES[i]||`Módulo ${i+1}`,summary:m.summary||m.resumo||String(m.content||m.conteudo||'').split(/\n+/).find(Boolean)||'',content:String(m.content||m.conteudo||''),imageDescription:m.imageDescription||m.descricaoImagem||m.title||m.titulo||'',imageQueries:m.imageQueries&&m.imageQueries.length?m.imageQueries:[m.title||m.titulo||'', 'embroidery textile craft'],fallbackImage:m.fallbackImage||svgData(m.title||m.titulo||`Módulo ${i+1}`),charCount:Number(m.charCount||m.totalCaracteres||String(m.content||m.conteudo||'').length),source:m.source||source})).filter(m=>m.id&&m.content);if(modules.length<1)throw new Error('Curso vazio');return modules}
function readCourseJson(){const p=path.join(ROOT,'data','curso-extraido.json');if(!fs.existsSync(p))throw new Error('data/curso-extraido.json não encontrado');const parsed=JSON.parse(fs.readFileSync(p,'utf8'));const modules=normalizeModules(parsed,'pdf-extraido');if(modules.length<30)throw new Error(`JSON do PDF incompleto: ${modules.length}/30 módulos`);courseSource='pdf-extraido';return modules}
function readCourseB64(){const dir=path.join(ROOT,'data');if(!fs.existsSync(dir))throw new Error('Diretório data não encontrado');const neutralKeys={'c08_0003.txt':'08.00.02.05.00.01.00.00.00.03','c08_0006.txt':'08.00.02.05.00.01.00.00.00.04','c08_0007.txt':'08.00.02.05.00.01.00.00.00.05'};const files=fs.readdirSync(dir).map(f=>{if(/^course-data\.b64\.\d+(?:\.\d+)*$/.test(f))return{f,key:f.replace(/^course-data\.b64\./,'')};if(neutralKeys[f])return{f,key:neutralKeys[f]};return null}).filter(Boolean).sort((a,b)=>a.key.localeCompare(b.key,undefined,{numeric:true}));if(!files.length)throw new Error('Chunks course-data.b64.* não encontrados');return files.map(x=>fs.readFileSync(path.join(dir,x.f),'utf8')).join('').replace(/\s+/g,'')}
function loadCourse(){if(courseCache)return courseCache;try{courseCache=readCourseJson();return courseCache}catch(e){console.warn('PDF extraído indisponível:',e.message)}try{const raw=zlib.gunzipSync(Buffer.from(readCourseB64(),'base64')).toString('utf8');const parsed=JSON.parse(raw);courseCache=normalizeModules(parsed,'uploaded-course-data');courseSource='uploaded-course-data';return courseCache}catch(e){console.error('Falha ao carregar course-data:',e.message);courseCache=fallbackCourse();return courseCache}}
function course(){return loadCourse()}
async function searchPexels(query,count=1){const q=clean(query||'embroidery textile craft',180);const n=Math.min(10,Math.max(1,Number(count)||1));const key='pexels:'+q.toLowerCase()+':'+n;if(imageCache.has(key))return imageCache.get(key);const fallback={query:q,images:[{url:svgData(q),thumb:svgData(q),photographer:'Fallback local',alt:q,fallback:true}],warning:''};const k=pexelsKey();if(!k){fallback.warning='PEXELS_API_KEY não configurada';imageCache.set(key,fallback);return fallback}try{const r=await fetch(`https://api.pexels.com/v1/search?query=${encodeURIComponent(q)}&per_page=${n}&orientation=landscape`,{headers:{Authorization:k}});const d=await r.json().catch(()=>({}));if(!r.ok){fallback.warning=d.error||'Erro Pexels '+r.status;imageCache.set(key,fallback);return fallback}const imgs=(d.photos||[]).map(p=>({url:p.src?.large2x||p.src?.large||p.src?.medium,thumb:p.src?.medium,photographer:p.photographer,alt:p.alt||q,source:p.url,fallback:false})).filter(x=>x.url);const data={query:q,images:imgs.length?imgs:fallback.images,warning:imgs.length?'':'Sem imagem no Pexels'};imageCache.set(key,data);return data}catch(e){fallback.warning=e.message;imageCache.set(key,fallback);return fallback}}
async function imageForModule(id){const m=course().find(x=>x.id===Number(id))||course()[0];const queries=[...(m.imageQueries||[]),m.imageDescription,m.title,'embroidery textile craft'].filter(Boolean);for(const q of queries){const data=await searchPexels(q,1);if(data.images?.[0]&&!data.images[0].fallback)return {moduleId:m.id,moduleTitle:m.title,query:data.query,image:data.images[0],warning:''}}const data=await searchPexels(queries[0],1);return {moduleId:m.id,moduleTitle:m.title,query:data.query,image:data.images[0],warning:data.warning||'Usando fallback local'}}
async function handleCourse(req,res){const u=new URL(req.url,`http://${req.headers.host}`);const c=course();if(u.pathname==='/api/course/index')return sendJson(res,200,{count:c.length,source:courseSource,modules:c.map(m=>({id:m.id,title:m.title,summary:m.summary,charCount:m.charCount,source:m.source,imageEndpoint:`/api/course/image?id=${m.id}`}))},'no-store');if(u.pathname==='/api/course/module'){const id=Number(u.searchParams.get('id')||1),m=c.find(x=>x.id===id)||c[id-1];if(!m)return sendJson(res,404,{error:'Módulo não encontrado'});return sendJson(res,200,{...m,imageEndpoint:`/api/course/image?id=${m.id}`},'no-store')}if(u.pathname==='/api/course/image')return sendJson(res,200,await imageForModule(Number(u.searchParams.get('id')||1)),'public, max-age=86400');if(u.pathname==='/api/course/images'){const items=[];for(const m of c)items.push(await imageForModule(m.id));return sendJson(res,200,{count:items.length,items},'public, max-age=86400')}return sendJson(res,404,{error:'Endpoint não encontrado'})}
async function handlePexels(req,res){const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/api/pexels/status'){const k=pexelsKey();return sendJson(res,200,{configured:!!k,length:k.length,prefix:k?k.slice(0,4):'',note:'O valor completo nunca é exposto.'})}return sendJson(res,200,await searchPexels(u.searchParams.get('query')||'embroidery',u.searchParams.get('per_page')||1),'public, max-age=86400')}
async function makeSpeechBuffer(input,voice,speed){const key=hash(JSON.stringify({input,voice,speed,model:process.env.OPENAI_TTS_MODEL||'gpt-4o-mini-tts'}));if(audioCache.has(key))return {buffer:audioCache.get(key),cached:true,key};const r=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_TTS_MODEL||'gpt-4o-mini-tts',input,voice,response_format:'mp3',speed,instructions:'Português do Brasil natural e didático.'})});if(!r.ok)throw new Error('Erro TTS '+r.status);const buffer=Buffer.from(await r.arrayBuffer());audioCache.set(key,buffer);if(audioCache.size>60)audioCache.delete(audioCache.keys().next().value);return {buffer,cached:false,key}}
async function handleTTS(req,res){if(!process.env.OPENAI_API_KEY)return sendJson(res,500,{error:'OPENAI_API_KEY não configurada'});if(req.method==='GET'){const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/api/tts/status')return sendJson(res,200,{cached:audioCache.size,mode:'memory-cache'});return sendJson(res,405,{error:'Use POST para gerar áudio'})}if(req.method!=='POST')return sendJson(res,405,{error:'Use POST'});let p;try{p=JSON.parse(await readBody(req))}catch{return sendJson(res,400,{error:'JSON inválido'})}const input=clean(p.text,4096),voice=p.voice||'coral',speed=Number(p.speed)||.95;try{const result=await makeSpeechBuffer(input,voice,speed);res.writeHead(200,{'Content-Type':'audio/mpeg','Cache-Control':'public, max-age=86400','X-Audio-Cache':result.cached?'HIT':'MISS','X-Audio-Key':result.key.slice(0,16)});res.end(result.buffer)}catch(e){sendJson(res,500,{error:e.message})}}
function extract(d){if(d.output_text)return d.output_text;return (d.output||[]).flatMap(o=>(o.content||[]).map(c=>c.text||c.output_text||'')).join('\n')}
async function handleAtelier(req,res){if(req.method!=='POST')return sendJson(res,405,{error:'Use POST'});if(!process.env.OPENAI_API_KEY)return sendJson(res,500,{error:'OPENAI_API_KEY não configurada'});let p;try{p=JSON.parse(await readBody(req))}catch{return sendJson(res,400,{error:'JSON inválido'})}const m=p.module||{},ctx=`Módulo: ${clean(m.title,200)}. Resumo: ${clean(m.summary,1000)}. Conteúdo: ${clean(m.content,2500)}. Pergunta: ${clean(p.prompt,1200)}.`;try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.5',instructions:'Você é uma professora especialista em bordado. Responda em português do Brasil com passos práticos e use apenas o contexto do módulo quando possível.',input:ctx})});const d=await r.json();if(!r.ok)return sendJson(res,r.status,{error:d?.error?.message||'Erro OpenAI'});return sendJson(res,200,{text:extract(d)||'Não consegui responder agora.'})}catch(e){return sendJson(res,500,{error:e.message})}}
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.pdf':'application/pdf'};
function serve(req,res){const u=new URL(req.url,`http://${req.headers.host}`);let p=decodeURIComponent(u.pathname);if(p==='/'||p==='/curso')p='/curso-completo.html';const f=path.normalize(path.join(ROOT,p));if(!f.startsWith(ROOT)){res.writeHead(403);return res.end('Forbidden')}fs.readFile(f,(e,d)=>{if(e){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Arquivo não encontrado.')}res.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream','Cache-Control':p.endsWith('.html')?'no-store':'public, max-age=3600'});res.end(d)})}
http.createServer((req,res)=>{if(req.url.startsWith('/api/course/'))return handleCourse(req,res);if(req.url.startsWith('/api/pexels'))return handlePexels(req,res);if(req.url.startsWith('/api/tts'))return handleTTS(req,res);if(req.url.startsWith('/api/atelier'))return handleAtelier(req,res);serve(req,res)}).listen(PORT,()=>console.log('Site rodando em http://localhost:'+PORT));
